import { ResourceAction, ResourceDefinition, ResourceField } from '@/features/shared/types/resource.types';
import { PermissionCode } from '@/types/erp';
const apiActionFromLabel = (label: string, statusTo: string) => {
    const normalizedLabel = label.toLowerCase();

    if (normalizedLabel.includes('bloquear crédito')) return 'bloquear-credito';
    if (normalizedLabel.includes('desbloquear crédito')) return 'desbloquear-credito';
    if (normalizedLabel.includes('enviar para aprovação')) return 'enviar-para-aprovacao';
    if (normalizedLabel.includes('aprovar')) return 'aprovar';
    if (normalizedLabel.includes('cancelar')) return 'cancelar';
    if (normalizedLabel.includes('inativar')) return 'inativar';
    if (normalizedLabel.includes('faturar')) return 'faturar';
    if (normalizedLabel.includes('baixar')) return 'baixar';
    if (normalizedLabel.includes('fechar')) return 'fechar';
    if (normalizedLabel.includes('receber')) return 'receber';
    if (normalizedLabel.includes('estornar recebimento')) return 'estornar-recebimento';
    if (normalizedLabel.includes('estornar pagamento')) return 'estornar-pagamento';
    if (normalizedLabel.includes('pagar')) return 'pagar';
    if (normalizedLabel.includes('bloquear')) return 'bloquear';

    return statusTo.toLowerCase().replace(/_/g, '-');
};

const statusAction = (permission: PermissionCode, label: string, statusTo: string, icon: string, severity: ResourceAction['severity'] = 'warning', requiresReason = true): ResourceAction => ({
    key: statusTo.toLowerCase().replace(/_/g, '-'),
    apiAction: apiActionFromLabel(label, statusTo),
    label,
    icon,
    permission,
    severity,
    requiresReason,
    statusTo,
    reasonLabel: `Motivo para ${label.toLowerCase()}`,
    successMessage: `${label} registrado com sucesso.`
});
const viewAction = (): ResourceAction => ({ key: 'visualizar', label: 'Detalhes', icon: 'pi pi-eye', severity: 'secondary' });
const editAction = (permission?: PermissionCode): ResourceAction => ({ key: 'editar', label: 'Editar', icon: 'pi pi-pencil', permission, severity: 'info', disabledWhen: ['INATIVO', 'CANCELADO', 'FATURADO', 'QUITADO', 'RECEBIDO_TOTAL', 'FECHADO'] });
const cadastroActions = (manage?: PermissionCode, inactivate?: PermissionCode): ResourceAction[] => [viewAction(), editAction(manage), statusAction(inactivate ?? manage ?? 'ADMINISTRACAO_GERENCIAR', 'Inativar', 'INATIVO', 'pi pi-ban', 'danger')];
const commonFields = (documentKind: 'cpfCnpj' | 'cnpj' | 'none' = 'none'): ResourceField[] => [
    { name: 'codigo', label: 'Código', kind: 'text', required: true, col: 'col-12 md:col-3' },
    { name: 'nome', label: 'Nome / descrição', kind: 'text', required: true, col: 'col-12 md:col-6' },
    ...(documentKind === 'cpfCnpj' ? [{ name: 'documento', label: 'Documento', kind: 'cpfCnpj' as const, required: true, helperText: 'CPF, CNPJ numérico ou CNPJ alfanumérico. Validação definitiva na API.' }] : []),
    ...(documentKind === 'cnpj' ? [{ name: 'documento', label: 'CNPJ', kind: 'cnpj' as const, required: true, helperText: 'Aceita CNPJ numérico e alfanumérico.' }] : []),
    { name: 'observacao', label: 'Observações', kind: 'textarea', col: 'col-12' }
];
const crud = (key: string, title: string, module: string, endpoint: string, viewPermission: PermissionCode, managePermission: PermissionCode, seed: Record<string, unknown>, doc: 'cpfCnpj' | 'cnpj' | 'none' = 'none', inactivate?: PermissionCode): ResourceDefinition => ({ key, title, module, endpoint, viewPermission, managePermission, description: `${title} com filtros, formulário, status, auditoria e ações protegidas por permissão.`, columns: [{ field: 'codigo', header: 'Código' }, { field: 'nome', header: title }, ...(doc === 'none' ? [] : [{ field: 'documento', header: 'Documento' }]), { field: 'status', header: 'Status', type: 'status' }], fields: commonFields(doc), rowActions: cadastroActions(managePermission, inactivate), initialData: [{ status: 'ATIVO', ...seed }] });
export const resourceCatalog: Record<string, ResourceDefinition> = {
    'seguranca-usuarios': { key: 'seguranca-usuarios', title: 'Usuários', module: 'Segurança', description: 'Gestão de usuários, sessão e vínculo com empresa/filial.', endpoint: '/api/seguranca/usuarios', viewPermission: 'SEGURANCA_USUARIOS_CONSULTAR', managePermission: 'SEGURANCA_USUARIOS_GERENCIAR', columns: [{ field: 'nome', header: 'Nome' }, { field: 'email', header: 'E-mail' }, { field: 'grupo', header: 'Grupo' }, { field: 'status', header: 'Status', type: 'status' }], fields: [{ name: 'nome', label: 'Nome', kind: 'text', required: true }, { name: 'email', label: 'E-mail', kind: 'text', required: true }, { name: 'grupo', label: 'Grupo de acesso', kind: 'select', required: true, options: [{ label: 'Administrador', value: 'Administrador' }, { label: 'Operacional', value: 'Operacional' }] }], rowActions: [viewAction(), editAction('SEGURANCA_USUARIOS_GERENCIAR'), statusAction('SEGURANCA_USUARIOS_GERENCIAR', 'Bloquear', 'BLOQUEADO', 'pi pi-lock', 'danger')], initialData: [{ id: 'usr-1', nome: 'Administrador logosoft', email: 'admin@logosoft.local', grupo: 'Administrador', status: 'ATIVO' }], criticalFlow: true },
    'seguranca-grupos': { key: 'seguranca-grupos', title: 'Grupos de acesso', module: 'Segurança', description: 'RBAC com permissões granulares por módulo, rota, botão e ação.', endpoint: '/api/seguranca/grupos-acesso', viewPermission: 'SEGURANCA_PERMISSOES_GERENCIAR', managePermission: 'SEGURANCA_PERMISSOES_GERENCIAR', columns: [{ field: 'nome', header: 'Grupo' }, { field: 'permissoes', header: 'Permissões', type: 'number' }, { field: 'status', header: 'Status', type: 'status' }], fields: [{ name: 'nome', label: 'Nome do grupo', kind: 'text', required: true }, { name: 'descricao', label: 'Descrição', kind: 'textarea' }, { name: 'permissoes', label: 'Quantidade de permissões', kind: 'number', required: true }], rowActions: cadastroActions('SEGURANCA_PERMISSOES_GERENCIAR'), initialData: [{ id: 'grp-1', nome: 'Administrador', permissoes: 44, status: 'ATIVO' }] },
    empresas: crud('empresas', 'Empresas', 'Administração', '/api/administracao/empresas', 'ADMINISTRACAO_CONSULTAR', 'ADMINISTRACAO_GERENCIAR', { id: 'emp-1', codigo: '001', nome: 'logosoft matriz', documento: '12ABC34501DE35' }, 'cnpj'),
    filiais: { ...crud('filiais', 'Filiais', 'Administração', '/api/administracao/filiais', 'ADMINISTRACAO_CONSULTAR', 'ADMINISTRACAO_GERENCIAR', { id: 'fil-1', codigo: '001', empresa: 'logosoft matriz', nome: 'Filial São Paulo', documento: '11222333000181' }, 'cnpj'), columns: [{ field: 'codigo', header: 'Código' }, { field: 'empresa', header: 'Empresa' }, { field: 'nome', header: 'Filial' }, { field: 'documento', header: 'CNPJ' }, { field: 'status', header: 'Status', type: 'status' }], fields: [{ name: 'empresa', label: 'Empresa', kind: 'text', required: true }, ...commonFields('cnpj')] },
    setores: crud('setores', 'Setores', 'Administração', '/api/administracao/setores', 'ADMINISTRACAO_CONSULTAR', 'ADMINISTRACAO_GERENCIAR', { id: 'set-1', codigo: 'ADM', nome: 'Administrativo' }),
    cargos: crud('cargos', 'Cargos', 'Administração', '/api/administracao/cargos', 'ADMINISTRACAO_CONSULTAR', 'ADMINISTRACAO_GERENCIAR', { id: 'car-1', codigo: 'GER', nome: 'Gerente' }),
    'centros-custo': crud('centros-custo', 'Centros de custo', 'Administração', '/api/administracao/centros-custo', 'ADMINISTRACAO_CONSULTAR', 'ADMINISTRACAO_GERENCIAR', { id: 'cc-1', codigo: 'ADM-001', nome: 'Administração geral' }),
    pessoas: { ...crud('pessoas', 'Pessoas', 'Cadastros', '/api/pessoas', 'PESSOAS_CONSULTAR', 'PESSOAS_GERENCIAR', { id: 'pes-1', codigo: 'P001', tipoPessoa: 'JURIDICA', nome: 'Cliente demonstração LTDA', documento: '12ABC34501DE35' }, 'cpfCnpj'), columns: [{ field: 'tipoPessoa', header: 'Tipo' }, { field: 'nome', header: 'Nome / Razão social' }, { field: 'documento', header: 'Documento' }, { field: 'status', header: 'Status', type: 'status' }], fields: [{ name: 'tipoPessoa', label: 'Tipo de pessoa', kind: 'select', required: true, options: [{ label: 'Pessoa física', value: 'FISICA' }, { label: 'Pessoa jurídica', value: 'JURIDICA' }] }, ...commonFields('cpfCnpj'), { name: 'email', label: 'E-mail principal', kind: 'text' }, { name: 'telefone', label: 'Telefone principal', kind: 'text' }], notes: ['Documentos podem ser mascarados por permissão futura.', 'Dados sensíveis não são enviados a logs.'], criticalFlow: true },
    clientes: { key: 'clientes', title: 'Clientes', module: 'Cadastros', endpoint: '/api/clientes', viewPermission: 'CLIENTES_CONSULTAR', managePermission: 'CLIENTES_GERENCIAR', description: 'Cadastro comercial com limite de crédito, bloqueio/desbloqueio e vínculo com pessoa.', columns: [{ field: 'codigo', header: 'Código' }, { field: 'pessoa', header: 'Pessoa' }, { field: 'limiteCredito', header: 'Limite', type: 'money' }, { field: 'statusCredito', header: 'Crédito', type: 'status' }, { field: 'status', header: 'Status', type: 'status' }], fields: [{ name: 'codigo', label: 'Código do cliente', kind: 'text', required: true }, { name: 'pessoa', label: 'Pessoa vinculada', kind: 'text', required: true }, { name: 'limiteCredito', label: 'Limite de crédito', kind: 'money' }, { name: 'statusCredito', label: 'Status do crédito', kind: 'select', options: [{ label: 'Liberado', value: 'LIBERADO' }, { label: 'Bloqueado', value: 'BLOQUEADO' }] }, { name: 'observacao', label: 'Observações comerciais', kind: 'textarea' }], rowActions: [viewAction(), editAction('CLIENTES_GERENCIAR'), statusAction('CLIENTES_GERENCIAR', 'Bloquear crédito', 'CREDITO_BLOQUEADO', 'pi pi-lock', 'danger'), statusAction('CLIENTES_GERENCIAR', 'Desbloquear crédito', 'CREDITO_LIBERADO', 'pi pi-lock-open', 'success'), statusAction('CLIENTES_GERENCIAR', 'Inativar', 'INATIVO', 'pi pi-ban', 'danger')], initialData: [{ id: 'cli-1', codigo: 'C0001', pessoa: 'Cliente demonstração LTDA', limiteCredito: 50000, statusCredito: 'LIBERADO', status: 'ATIVO' }], criticalFlow: true },
    fornecedores: { key: 'fornecedores', title: 'Fornecedores', module: 'Cadastros', endpoint: '/api/fornecedores', viewPermission: 'FORNECEDORES_CONSULTAR', managePermission: 'FORNECEDORES_GERENCIAR', description: 'Cadastro de fornecedores para compras, financeiro e fiscal.', columns: [{ field: 'codigo', header: 'Código' }, { field: 'pessoa', header: 'Pessoa' }, { field: 'contatoComercial', header: 'Contato' }, { field: 'status', header: 'Status', type: 'status' }], fields: [{ name: 'codigo', label: 'Código do fornecedor', kind: 'text', required: true }, { name: 'pessoa', label: 'Pessoa vinculada', kind: 'text', required: true }, { name: 'contatoComercial', label: 'Contato comercial', kind: 'text' }, { name: 'observacao', label: 'Observações', kind: 'textarea' }], rowActions: cadastroActions('FORNECEDORES_GERENCIAR'), initialData: [{ id: 'for-1', codigo: 'F0001', pessoa: 'Fornecedor base SA', contatoComercial: 'compras@fornecedor.local', status: 'ATIVO' }], criticalFlow: true },
    produtos: { key: 'produtos', title: 'Produtos', module: 'Produtos', endpoint: '/api/produtos', viewPermission: 'PRODUTOS_CONSULTAR', managePermission: 'PRODUTOS_GERENCIAR', description: 'Catálogo com dados comerciais, fiscais, estoque, compra e venda.', columns: [{ field: 'codigo', header: 'Código' }, { field: 'nome', header: 'Descrição' }, { field: 'unidadeMedida', header: 'Un.' }, { field: 'precoVenda', header: 'Preço', type: 'money' }, { field: 'controlaEstoque', header: 'Estoque?', type: 'boolean' }, { field: 'status', header: 'Status', type: 'status' }], fields: [{ name: 'codigo', label: 'Código', kind: 'text', required: true }, { name: 'nome', label: 'Descrição', kind: 'text', required: true }, { name: 'unidadeMedida', label: 'Unidade de medida', kind: 'text', required: true }, { name: 'categoria', label: 'Categoria', kind: 'text' }, { name: 'marca', label: 'Marca', kind: 'text' }, { name: 'precoVenda', label: 'Preço de venda', kind: 'money' }, { name: 'custoReferencial', label: 'Custo referencial', kind: 'money' }, { name: 'controlaEstoque', label: 'Controla estoque', kind: 'checkbox' }, { name: 'permiteVenda', label: 'Permite venda', kind: 'checkbox' }, { name: 'permiteCompra', label: 'Permite compra', kind: 'checkbox' }, { name: 'ncm', label: 'NCM', kind: 'text', permission: 'PRODUTOS_DADOS_FISCAIS_GERENCIAR' }, { name: 'cest', label: 'CEST', kind: 'text', permission: 'PRODUTOS_DADOS_FISCAIS_GERENCIAR' }], rowActions: cadastroActions('PRODUTOS_GERENCIAR', 'PRODUTOS_INATIVAR'), initialData: [{ id: 'prd-1', codigo: 'PRD-001', nome: 'Produto demonstração', unidadeMedida: 'UN', categoria: 'Geral', precoVenda: 129.9, custoReferencial: 70, controlaEstoque: true, permiteVenda: true, permiteCompra: true, status: 'ATIVO' }], criticalFlow: true },
    categorias: crud('categorias', 'Categorias de produto', 'Produtos', '/api/produtos/categorias', 'PRODUTOS_CONSULTAR', 'CATEGORIAS_PRODUTO_GERENCIAR', { id: 'cat-1', codigo: 'GERAL', nome: 'Geral' }),
    'unidades-medida': crud('unidades-medida', 'Unidades de medida', 'Produtos', '/api/produtos/unidades-medida', 'PRODUTOS_CONSULTAR', 'UNIDADES_MEDIDA_GERENCIAR', { id: 'un-1', codigo: 'UN', nome: 'Unidade' }),
    marcas: { ...crud('marcas', 'Marcas', 'Produtos', '/api/produtos/marcas', 'PRODUTOS_CONSULTAR', 'MARCAS_GERENCIAR', { id: 'mar-1', codigo: 'M01', nome: 'Marca padrão' }), fields: [{ name: 'nome', label: 'Nome da marca', kind: 'text', required: true }, { name: 'observacao', label: 'Observações', kind: 'textarea' }] },
    'estoque-locais': crud('estoque-locais', 'Locais de estoque', 'Estoque', '/api/estoque/locais', 'ESTOQUE_CONSULTAR', 'LOCAIS_ESTOQUE_GERENCIAR', { id: 'loc-1', codigo: 'ALM-01', nome: 'Almoxarifado principal' }),
    'estoque-saldos': { key: 'estoque-saldos', title: 'Saldos de estoque', module: 'Estoque', description: 'Consulta de saldo atual, reservado e disponível. Saldo não é alterado diretamente.', endpoint: '/api/estoque/saldos', viewPermission: 'ESTOQUE_CONSULTAR', columns: [{ field: 'produto', header: 'Produto' }, { field: 'localEstoque', header: 'Local' }, { field: 'saldoAtual', header: 'Atual', type: 'number' }, { field: 'saldoReservado', header: 'Reservado', type: 'number' }, { field: 'saldoDisponivel', header: 'Disponível', type: 'number' }], fields: [{ name: 'produto', label: 'Produto', kind: 'text' }, { name: 'localEstoque', label: 'Local', kind: 'text' }], rowActions: [viewAction()], initialData: [{ id: 'sal-1', produto: 'Produto demonstração', localEstoque: 'Almoxarifado principal', saldoAtual: 100, saldoReservado: 10, saldoDisponivel: 90, status: 'ATIVO' }], notes: ['Saldo é consequência de movimentos. Esta tela é de consulta.'], criticalFlow: true },
    'estoque-movimentos': { key: 'estoque-movimentos', title: 'Movimentos de estoque', module: 'Estoque', description: 'Rastreabilidade de entradas, saídas, ajustes, reservas e baixas.', endpoint: '/api/estoque/movimentos', viewPermission: 'ESTOQUE_CONSULTAR', columns: [{ field: 'tipo', header: 'Tipo', type: 'status' }, { field: 'produto', header: 'Produto' }, { field: 'localEstoque', header: 'Local' }, { field: 'quantidade', header: 'Quantidade', type: 'number' }, { field: 'origem', header: 'Origem' }], fields: [{ name: 'tipo', label: 'Tipo', kind: 'text' }, { name: 'produto', label: 'Produto', kind: 'text' }], rowActions: [viewAction()], initialData: [{ id: 'mov-1', tipo: 'ENTRADA', produto: 'Produto demonstração', localEstoque: 'Almoxarifado principal', quantidade: 100, origem: 'Seed', status: 'PROCESSADO' }], criticalFlow: true },
    'estoque-entradas': { key: 'estoque-entradas', title: 'Entrada de estoque', module: 'Estoque', description: 'Entrada manual com geração de movimento e auditoria.', endpoint: '/api/estoque/entradas', viewPermission: 'ESTOQUE_MOVIMENTAR', managePermission: 'ESTOQUE_MOVIMENTAR', columns: [{ field: 'produto', header: 'Produto' }, { field: 'localEstoque', header: 'Local' }, { field: 'quantidade', header: 'Quantidade', type: 'number' }, { field: 'status', header: 'Status', type: 'status' }], fields: [{ name: 'produto', label: 'Produto', kind: 'text', required: true }, { name: 'localEstoque', label: 'Local', kind: 'text', required: true }, { name: 'quantidade', label: 'Quantidade', kind: 'number', required: true }, { name: 'motivo', label: 'Motivo/documento', kind: 'textarea', required: true }], rowActions: [viewAction()], initialData: [{ id: 'ent-1', produto: 'Produto demonstração', localEstoque: 'Almoxarifado principal', quantidade: 100, status: 'PROCESSADO' }], criticalFlow: true },
    'estoque-saidas': { key: 'estoque-saidas', title: 'Saída de estoque', module: 'Estoque', description: 'Saída manual com validação de saldo disponível pela API.', endpoint: '/api/estoque/saidas', viewPermission: 'ESTOQUE_MOVIMENTAR', managePermission: 'ESTOQUE_MOVIMENTAR', columns: [{ field: 'produto', header: 'Produto' }, { field: 'localEstoque', header: 'Local' }, { field: 'quantidade', header: 'Quantidade', type: 'number' }, { field: 'status', header: 'Status', type: 'status' }], fields: [{ name: 'produto', label: 'Produto', kind: 'text', required: true }, { name: 'localEstoque', label: 'Local', kind: 'text', required: true }, { name: 'quantidade', label: 'Quantidade', kind: 'number', required: true }, { name: 'motivo', label: 'Motivo/documento', kind: 'textarea', required: true }], rowActions: [viewAction()], initialData: [{ id: 'sai-1', produto: 'Produto demonstração', localEstoque: 'Almoxarifado principal', quantidade: 5, status: 'PROCESSADO' }], criticalFlow: true },
    'estoque-ajustes': { key: 'estoque-ajustes', title: 'Ajustes de estoque', module: 'Estoque', description: 'Ajuste controlado com motivo obrigatório e auditoria.', endpoint: '/api/estoque/ajustes', viewPermission: 'ESTOQUE_MOVIMENTAR', managePermission: 'ESTOQUE_MOVIMENTAR', columns: [{ field: 'produto', header: 'Produto' }, { field: 'localEstoque', header: 'Local' }, { field: 'quantidade', header: 'Quantidade', type: 'number' }, { field: 'motivo', header: 'Motivo' }, { field: 'status', header: 'Status', type: 'status' }], fields: [{ name: 'produto', label: 'Produto', kind: 'text', required: true }, { name: 'localEstoque', label: 'Local', kind: 'text', required: true }, { name: 'quantidade', label: 'Quantidade ajustada', kind: 'number', required: true }, { name: 'motivo', label: 'Motivo do ajuste', kind: 'textarea', required: true }], rowActions: [viewAction()], initialData: [{ id: 'aju-1', produto: 'Produto demonstração', localEstoque: 'Almoxarifado principal', quantidade: 2, motivo: 'Conferência', status: 'PROCESSADO' }] },
    'estoque-reservas': { key: 'estoque-reservas', title: 'Reservas de estoque', module: 'Estoque', description: 'Reserva, baixa e cancelamento com impacto de saldo.', endpoint: '/api/estoque/reservas', viewPermission: 'ESTOQUE_CONSULTAR', managePermission: 'ESTOQUE_RESERVAR', columns: [{ field: 'produto', header: 'Produto' }, { field: 'localEstoque', header: 'Local' }, { field: 'quantidade', header: 'Quantidade', type: 'number' }, { field: 'origem', header: 'Origem' }, { field: 'status', header: 'Status', type: 'status' }], fields: [{ name: 'produto', label: 'Produto', kind: 'text', required: true }, { name: 'localEstoque', label: 'Local', kind: 'text', required: true }, { name: 'quantidade', label: 'Quantidade', kind: 'number', required: true }, { name: 'origem', label: 'Origem', kind: 'text' }], rowActions: [viewAction(), statusAction('ESTOQUE_RESERVAR', 'Baixar reserva', 'BAIXADA', 'pi pi-check', 'success'), statusAction('ESTOQUE_RESERVAR', 'Cancelar reserva', 'CANCELADA', 'pi pi-times', 'danger')], initialData: [{ id: 'res-1', produto: 'Produto demonstração', localEstoque: 'Almoxarifado principal', quantidade: 10, origem: 'Pedido venda PV-001', status: 'RESERVADA' }], criticalFlow: true },
    'estoque-inventarios': { key: 'estoque-inventarios', title: 'Inventários', module: 'Estoque', description: 'Abertura, contagem, fechamento e cancelamento de inventário.', endpoint: '/api/estoque/inventarios', viewPermission: 'ESTOQUE_CONSULTAR', managePermission: 'ESTOQUE_INVENTARIO_GERENCIAR', columns: [{ field: 'codigo', header: 'Código' }, { field: 'localEstoque', header: 'Local' }, { field: 'itens', header: 'Itens', type: 'number' }, { field: 'status', header: 'Status', type: 'status' }], fields: [{ name: 'codigo', label: 'Código', kind: 'text', required: true }, { name: 'localEstoque', label: 'Local', kind: 'text', required: true }, { name: 'itens', label: 'Itens previstos', kind: 'number' }, { name: 'observacao', label: 'Observações', kind: 'textarea' }], rowActions: [viewAction(), editAction('ESTOQUE_INVENTARIO_GERENCIAR'), statusAction('ESTOQUE_INVENTARIO_GERENCIAR', 'Fechar inventário', 'FECHADO', 'pi pi-check-circle', 'success'), statusAction('ESTOQUE_INVENTARIO_GERENCIAR', 'Cancelar inventário', 'CANCELADO', 'pi pi-times', 'danger')], initialData: [{ id: 'inv-1', codigo: 'INV-001', localEstoque: 'Almoxarifado principal', itens: 1, status: 'ABERTO' }], criticalFlow: true },
    'vendas-pedidos': { key: 'vendas-pedidos', title: 'Pedidos de venda', module: 'Vendas', description: 'Pedido de venda com rascunho, aprovação, reserva/baixa e faturamento lógico.', endpoint: '/api/vendas/pedidos', viewPermission: 'VENDAS_CONSULTAR', managePermission: 'VENDAS_GERENCIAR', columns: [{ field: 'codigo', header: 'Pedido' }, { field: 'cliente', header: 'Cliente' }, { field: 'itens', header: 'Itens', type: 'number' }, { field: 'total', header: 'Total', type: 'money' }, { field: 'status', header: 'Status', type: 'status' }], fields: [{ name: 'codigo', label: 'Número', kind: 'text', required: true }, { name: 'cliente', label: 'Cliente', kind: 'text', required: true }, { name: 'itens', label: 'Quantidade de itens', kind: 'number', required: true }, { name: 'total', label: 'Total', kind: 'money', required: true }, { name: 'observacao', label: 'Observações', kind: 'textarea' }], rowActions: [viewAction(), editAction('VENDAS_GERENCIAR'), statusAction('VENDAS_GERENCIAR', 'Enviar para aprovação', 'ENVIADO_APROVACAO', 'pi pi-send', 'info', false), statusAction('VENDAS_APROVAR', 'Aprovar', 'APROVADO', 'pi pi-check', 'success', false), statusAction('VENDAS_CANCELAR', 'Cancelar', 'CANCELADO', 'pi pi-times', 'danger'), statusAction('VENDAS_FATURAR', 'Faturar', 'FATURADO', 'pi pi-file-export', 'success', false)], initialData: [{ id: 'pv-1', codigo: 'PV-001', cliente: 'Cliente demonstração LTDA', itens: 2, total: 259.8, status: 'RASCUNHO' }], notes: ['O backend valida saldo, cliente, produto ativo e permissões.', 'Faturamento pode gerar financeiro, estoque e fiscal conforme retorno da API.'], criticalFlow: true },
    'financeiro-formas-pagamento': { key: 'financeiro-formas-pagamento', title: 'Formas de pagamento', module: 'Financeiro', description: 'Formas configuráveis para recebimentos e pagamentos.', endpoint: '/api/financeiro/formas-pagamento', viewPermission: 'FINANCEIRO_CONSULTAR', managePermission: 'FORMAS_PAGAMENTO_GERENCIAR', columns: [{ field: 'nome', header: 'Forma' }, { field: 'permiteReceber', header: 'Receber?', type: 'boolean' }, { field: 'permitePagar', header: 'Pagar?', type: 'boolean' }, { field: 'status', header: 'Status', type: 'status' }], fields: [{ name: 'nome', label: 'Forma de pagamento', kind: 'text', required: true }, { name: 'permiteReceber', label: 'Permite receber', kind: 'checkbox' }, { name: 'permitePagar', label: 'Permite pagar', kind: 'checkbox' }], rowActions: cadastroActions('FORMAS_PAGAMENTO_GERENCIAR'), initialData: [{ id: 'fp-1', nome: 'PIX', permiteReceber: true, permitePagar: true, status: 'ATIVO' }] },
    'financeiro-condicoes-pagamento': { key: 'financeiro-condicoes-pagamento', title: 'Condições de pagamento', module: 'Financeiro', description: 'Parcelamento com quantidade e intervalo controlados.', endpoint: '/api/financeiro/condicoes-pagamento', viewPermission: 'FINANCEIRO_CONSULTAR', managePermission: 'CONDICOES_PAGAMENTO_GERENCIAR', columns: [{ field: 'nome', header: 'Condição' }, { field: 'parcelas', header: 'Parcelas', type: 'number' }, { field: 'intervaloDias', header: 'Intervalo', type: 'number' }, { field: 'status', header: 'Status', type: 'status' }], fields: [{ name: 'nome', label: 'Condição', kind: 'text', required: true }, { name: 'parcelas', label: 'Parcelas', kind: 'number', required: true }, { name: 'intervaloDias', label: 'Intervalo em dias', kind: 'number', required: true }], rowActions: cadastroActions('CONDICOES_PAGAMENTO_GERENCIAR'), initialData: [{ id: 'cond-1', nome: '30/60/90', parcelas: 3, intervaloDias: 30, status: 'ATIVO' }] },
    'financeiro-contas-receber': { key: 'financeiro-contas-receber', title: 'Contas a receber', module: 'Financeiro', description: 'Recebimentos parciais/totais, saldo, estorno e cancelamento.', endpoint: '/api/financeiro/contas-receber', viewPermission: 'FINANCEIRO_CONSULTAR', managePermission: 'FINANCEIRO_GERENCIAR', columns: [{ field: 'codigo', header: 'Documento' }, { field: 'cliente', header: 'Cliente' }, { field: 'valorTotal', header: 'Valor', type: 'money' }, { field: 'saldo', header: 'Saldo', type: 'money' }, { field: 'status', header: 'Status', type: 'status' }], fields: [{ name: 'codigo', label: 'Documento', kind: 'text', required: true }, { name: 'cliente', label: 'Cliente', kind: 'text', required: true }, { name: 'valorTotal', label: 'Valor total', kind: 'money', required: true }, { name: 'saldo', label: 'Saldo', kind: 'money', required: true }, { name: 'origem', label: 'Origem', kind: 'text' }], rowActions: [viewAction(), statusAction('FINANCEIRO_RECEBER', 'Receber parcial', 'PARCIAL', 'pi pi-dollar', 'success', false), statusAction('FINANCEIRO_RECEBER', 'Receber total', 'QUITADO', 'pi pi-check-circle', 'success', false), statusAction('FINANCEIRO_ESTORNAR', 'Estornar recebimento', 'ESTORNADO', 'pi pi-undo', 'warning'), statusAction('FINANCEIRO_CANCELAR', 'Cancelar', 'CANCELADO', 'pi pi-times', 'danger')], initialData: [{ id: 'cr-1', codigo: 'CR-PV-001', cliente: 'Cliente demonstração LTDA', valorTotal: 259.8, saldo: 259.8, origem: 'Pedido venda PV-001', status: 'ABERTO' }], criticalFlow: true },
    'financeiro-contas-pagar': { key: 'financeiro-contas-pagar', title: 'Contas a pagar', module: 'Financeiro', description: 'Pagamentos parciais/totais, saldo, estorno e cancelamento.', endpoint: '/api/financeiro/contas-pagar', viewPermission: 'FINANCEIRO_CONSULTAR', managePermission: 'FINANCEIRO_GERENCIAR', columns: [{ field: 'codigo', header: 'Documento' }, { field: 'fornecedor', header: 'Fornecedor' }, { field: 'valorTotal', header: 'Valor', type: 'money' }, { field: 'saldo', header: 'Saldo', type: 'money' }, { field: 'status', header: 'Status', type: 'status' }], fields: [{ name: 'codigo', label: 'Documento', kind: 'text', required: true }, { name: 'fornecedor', label: 'Fornecedor', kind: 'text', required: true }, { name: 'valorTotal', label: 'Valor total', kind: 'money', required: true }, { name: 'saldo', label: 'Saldo', kind: 'money', required: true }, { name: 'origem', label: 'Origem', kind: 'text' }], rowActions: [viewAction(), statusAction('FINANCEIRO_PAGAR', 'Pagar parcial', 'PARCIAL', 'pi pi-dollar', 'success', false), statusAction('FINANCEIRO_PAGAR', 'Pagar total', 'QUITADO', 'pi pi-check-circle', 'success', false), statusAction('FINANCEIRO_ESTORNAR', 'Estornar pagamento', 'ESTORNADO', 'pi pi-undo', 'warning'), statusAction('FINANCEIRO_CANCELAR', 'Cancelar', 'CANCELADO', 'pi pi-times', 'danger')], initialData: [{ id: 'cpag-1', codigo: 'CP-PC-001', fornecedor: 'Fornecedor base SA', valorTotal: 800, saldo: 800, origem: 'Pedido compra PC-001', status: 'ABERTO' }], criticalFlow: true },
    'compras-pedidos': { key: 'compras-pedidos', title: 'Pedidos de compra', module: 'Compras', description: 'Pedido de compra com aprovação, recebimento parcial/total, estoque e financeiro.', endpoint: '/api/compras/pedidos', viewPermission: 'COMPRAS_CONSULTAR', managePermission: 'COMPRAS_GERENCIAR', columns: [{ field: 'codigo', header: 'Pedido' }, { field: 'fornecedor', header: 'Fornecedor' }, { field: 'itens', header: 'Itens', type: 'number' }, { field: 'total', header: 'Total', type: 'money' }, { field: 'status', header: 'Status', type: 'status' }], fields: [{ name: 'codigo', label: 'Número', kind: 'text', required: true }, { name: 'fornecedor', label: 'Fornecedor', kind: 'text', required: true }, { name: 'itens', label: 'Quantidade de itens', kind: 'number', required: true }, { name: 'total', label: 'Total', kind: 'money', required: true }, { name: 'gerarContaPagar', label: 'Gerar conta a pagar no recebimento', kind: 'checkbox' }, { name: 'permiteReceberAcima', label: 'Permitir recebimento acima do pedido', kind: 'checkbox' }, { name: 'observacao', label: 'Observações', kind: 'textarea' }], rowActions: [viewAction(), editAction('COMPRAS_GERENCIAR'), statusAction('COMPRAS_GERENCIAR', 'Enviar para aprovação', 'ENVIADO_APROVACAO', 'pi pi-send', 'info', false), statusAction('COMPRAS_APROVAR', 'Aprovar', 'APROVADO', 'pi pi-check', 'success', false), statusAction('COMPRAS_RECEBER', 'Receber parcial', 'RECEBIDO_PARCIAL', 'pi pi-box', 'success', false), statusAction('COMPRAS_RECEBER', 'Receber total', 'RECEBIDO_TOTAL', 'pi pi-check-circle', 'success', false), statusAction('COMPRAS_CANCELAR', 'Cancelar', 'CANCELADO', 'pi pi-times', 'danger')], initialData: [{ id: 'pc-1', codigo: 'PC-001', fornecedor: 'Fornecedor base SA', itens: 3, total: 800, gerarContaPagar: true, status: 'RASCUNHO' }], criticalFlow: true },
    'auditoria-eventos': { key: 'auditoria-eventos', title: 'Eventos de auditoria', module: 'Auditoria', description: 'Consulta de eventos operacionais críticos.', endpoint: '/api/auditoria/eventos', viewPermission: 'AUDITORIA_CONSULTAR', columns: [{ field: 'modulo', header: 'Módulo' }, { field: 'acao', header: 'Ação' }, { field: 'usuario', header: 'Usuário' }, { field: 'criadoEm', header: 'Criado em', type: 'datetime' }], fields: [{ name: 'modulo', label: 'Módulo', kind: 'text' }, { name: 'acao', label: 'Ação', kind: 'text' }, { name: 'usuario', label: 'Usuário', kind: 'text' }], rowActions: [viewAction()], initialData: [{ id: 'aud-1', modulo: 'Auth', acao: 'Login realizado', usuario: 'Administrador logosoft', criadoEm: new Date().toISOString(), status: 'REGISTRADO' }] }
};
export const getResourceDefinition = (key: string) => {
    const definition = resourceCatalog[key];
    if (!definition) throw new Error(`Recurso não catalogado: ${key}`);
    return definition;
};
