'use client';
import { useMemo, useState } from 'react';
import { Button } from 'primereact/button';
import { Card } from 'primereact/card';
import { Column } from 'primereact/column';
import { SearchInput } from '@/components/forms/SearchInput';
import { Message } from 'primereact/message';
import { Dialog } from 'primereact/dialog';
import { PageHeader } from '@/components/common/PageHeader';
import { AuditInfoPanel } from '@/components/common/AuditInfoPanel';
import { StatusHistoryPanel } from '@/components/common/StatusHistoryPanel';
import { DataTableActions } from '@/components/data/DataTableActions';
import { DataTableServer } from '@/components/data/DataTableServer';
import { StatusTag } from '@/components/data/StatusTag';
import { EmptyState } from '@/components/feedback/EmptyState';
import { ReasonDialog } from '@/components/feedback/ReasonDialog';
import { UnauthorizedState } from '@/components/feedback/UnauthorizedState';
import { PermissionGuard } from '@/components/security/PermissionGuard';
import { usePermissions } from '@/features/auth/hooks/usePermissions';
import { DynamicResourceForm } from '@/features/shared/components/DynamicResourceForm';
import { getResourceDefinition } from '@/features/shared/config/erpFeatureCatalog';
import { useResourceController } from '@/features/shared/hooks/useResourceController';
import { ResourceAction, ResourceDefinition, ResourceSavePayload } from '@/features/shared/types/resource.types';
import { canRunActionByStatus } from '@/features/shared/utils/statusRules';
import { useMutationWithToast } from '@/hooks/useMutationWithToast';
import { AuditInfo, StatusHistoryItem } from '@/types/erp';
import { formatDisplayValue } from '@/lib/formatters/display';
const formatValue = formatDisplayValue;
const ResourceNotes = ({ definition }: { definition: ResourceDefinition }) => definition.notes?.length ? <div className="mb-3">{definition.notes.map((note) => <Message key={note} severity="info" text={note} className="w-full mb-2" />)}</div> : null;
export const EntityManagementPage = ({ resourceKey }: { resourceKey: string }) => {
    const definition = useMemo(() => getResourceDefinition(resourceKey), [resourceKey]); const { hasPermission } = usePermissions(); const runWithToast = useMutationWithToast(); const { query, setQuery, listQuery, saveMutation, actionMutation } = useResourceController(definition);
    const [formVisible, setFormVisible] = useState(false); const [selectedRecord, setSelectedRecord] = useState<Record<string, unknown> | null>(null); const [detailsRecord, setDetailsRecord] = useState<Record<string, unknown> | null>(null); const [reasonState, setReasonState] = useState<{ record: Record<string, unknown>; action: ResourceAction } | null>(null);
    if (!hasPermission(definition.viewPermission)) return <UnauthorizedState description={`A rotina ${definition.title} exige a permissão ${definition.viewPermission}.`} />;
    const rows = listQuery.data?.items ?? []; const totalRecords = listQuery.data?.totalItems ?? 0;
    const openNew = () => { setSelectedRecord(null); setFormVisible(true); }; const openEdit = (record: Record<string, unknown>) => { setSelectedRecord(record); setFormVisible(true); };
    const saveRecord = async (payload: ResourceSavePayload) => { await runWithToast(async () => { await saveMutation.mutateAsync(payload); setFormVisible(false); setSelectedRecord(null); }, { success: { summary: 'Registro salvo', detail: `${definition.title}: operação concluída com sucesso.` }, error: { summary: 'Erro ao salvar', detail: 'Não foi possível salvar o registro.' } }); };
    const runAction = async (record: Record<string, unknown>, action: ResourceAction, reason?: string) => { await runWithToast(async () => { await actionMutation.mutateAsync({ id: String(record.id), action, reason }); setReasonState(null); }, { success: { summary: 'Operação realizada', detail: action.successMessage ?? `${action.label} concluído.` }, error: { summary: 'Erro operacional', detail: 'Não foi possível executar a ação.' } }); };
    const handleAction = (record: Record<string, unknown>, action: ResourceAction) => { if (action.key === 'visualizar') { setDetailsRecord(record); return; } if (action.key === 'editar') { openEdit(record); return; } if (action.requiresReason) { setReasonState({ record, action }); return; } void runAction(record, action); };
    const headerActions = <><SearchInput ariaLabel="Buscar" defaultValue={query.search ?? ''} onChange={(term) => setQuery((current) => ({ ...current, page: 1, search: term }))} />{definition.managePermission ? <PermissionGuard permission={definition.managePermission} mode="disable">{({ disabled }) => <Button label="Novo" icon="pi pi-plus" onClick={openNew} disabled={disabled} />}</PermissionGuard> : null}</>;
    return <><PageHeader title={definition.title} description={definition.description} actions={headerActions} /><ResourceNotes definition={definition} /><Card><DataTableServer value={rows} totalRecords={totalRecords} loading={listQuery.isLoading} first={((query.page ?? 1) - 1) * (query.pageSize ?? 10)} rows={query.pageSize ?? 10} sortField={query.sortField} sortOrder={query.sortOrder} onPage={(event) => setQuery((current) => ({ ...current, page: Math.floor(event.first / event.rows) + 1, pageSize: event.rows }))} onSort={(event) => setQuery((current) => ({ ...current, sortField: event.sortField, sortOrder: event.sortOrder }))} emptyMessage="Nenhum registro encontrado para os filtros informados.">{definition.columns.map((column) => <Column key={column.field} field={column.field} header={column.header} sortable={column.sortable} body={(row: Record<string, unknown>) => column.type === 'status' ? <StatusTag status={String(row[column.field] ?? '')} /> : formatValue(row[column.field], column.type)} />)}<Column header="Ações" alignHeader="right" body={(row: Record<string, unknown>) => <DataTableActions actions={definition.rowActions.map((action) => ({ key: action.key, label: action.label, icon: action.icon, permission: action.permission, severity: action.severity, disabled: !canRunActionByStatus(action, String(row.status ?? 'ATIVO')), onClick: () => handleAction(row, action) }))} />} /></DataTableServer>{!listQuery.isLoading && rows.length === 0 ? <EmptyState title="Nenhum registro" description="Crie um novo registro ou ajuste os filtros de busca." /> : null}</Card><DynamicResourceForm definition={definition} visible={formVisible} record={selectedRecord} loading={saveMutation.isPending} onHide={() => setFormVisible(false)} onSubmit={saveRecord} /><ReasonDialog visible={Boolean(reasonState)} title={reasonState?.action.reasonLabel ?? 'Motivo obrigatório'} confirmLabel={reasonState?.action.label ?? 'Confirmar'} loading={actionMutation.isPending} onHide={() => setReasonState(null)} onConfirm={(reason) => reasonState && void runAction(reasonState.record, reasonState.action, reason)} /><Dialog header="Detalhes e auditoria" visible={Boolean(detailsRecord)} style={{ width: 'min(56rem, 96vw)' }} modal onHide={() => setDetailsRecord(null)}>{detailsRecord ? <div className="grid"><div className="col-12 lg:col-7"><Card title="Dados do registro"><dl className="grid m-0 line-height-3">{definition.columns.map((column) => <div className="col-12 md:col-6" key={column.field}><dt className="font-semibold">{column.header}</dt><dd className="m-0">{formatValue(detailsRecord[column.field], column.type)}</dd></div>)}</dl></Card></div><div className="col-12 lg:col-5 flex flex-column gap-3"><AuditInfoPanel audit={detailsRecord.auditoria as AuditInfo | undefined} /><StatusHistoryPanel history={detailsRecord.historicoStatus as StatusHistoryItem[] | undefined} /></div></div> : null}</Dialog></>;
};
